### ISSUE TITLE
不好意思我看错了-。-

### ISSUE THREAD

**Issue by JialingRichard** [misaka10843/genshin-server-switching#1]
~~每过一两个月他的版本号都要变一下，我觉得改起来还是挺麻烦的，而且如果匹配不成功还不是要自己在源文件里面改了过后再编译（如果不会c语言的同学那就更麻烦了）。所以私以为可以改下代码，如果匹配不成功直接命令行提示一下然后继续运行即可。然后sleep(5000)会不会等的有点长啊>.<。~~
最后感谢你的分享让我少下了十几个g的游戏。

**Comment by misaka10843** [comment]
> 

( •̀ ω •́ )✧

**Comment by misaka10843** [comment]
其实当初从C++转python就已经知道有这些问题才转的www
（因为我并不怎么会C++qwq）


> ~每过一两个月他的版本号都要变一下，我觉得改起来还是挺麻烦的，而且如果匹配不成功还不是要自己在源文件里面改了过后再编译（如果不会c语言的同学那就更麻烦了）。所以私以为可以改下代码，如果匹配不成功直接命令行提示一下然后继续运行即可。然后sleep(5000)会不会等的有点长啊>.<。~ 最后感谢你的分享让我少下了十几个g的游戏。
