### ISSUE TITLE
路径不对

### ISSUE THREAD

**Issue by tntcoc** [misaka10843/genshin-server-switching#5]
![1647772925(1)](https://user-images.githubusercontent.com/70332409/159158547-31ffb469-7842-4eba-9e36-65d511dfe971.jpg)
没明白是哪里的问题

**Comment by misaka10843** [comment]
最好还是复制这个路径后在资源管理器中试试能不能转到那里qwq

（但是也可能是此路径内没有yuanshen.exe）

**Comment by misaka10843** [comment]
因为没有给出详细信息，所以并不能查找原因，暂时关闭此issue
